sonar.projectKey=beymarcastillo-star_Sistema-Crediticio-BDP.2.0
sonar.organization=beymarcastillo-star

sonar.projectName=Sistema Crediticio BDP
sonar.projectVersion=2.0

sonar.sources=.
sonar.exclusions=**/*.md,docs/**,**/__pycache__/**,**/*.txt,**/*.yml,**/*.yaml,**/*.pdf,**/*.docx
